#!/usr/bin/env bash

# Update package lists and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set the X-Served-By custom header in the nginx config for both servers
sudo sed -i '/server_name_in_redirect off;/a \    add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx

