#!/usr/bin/env bash
# Symlink default Nginx config
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx service
sudo service nginx restart
# Stop Nginx service explicitly
sudo service nginx stop
