#!/usr/bin/env bash

# Stop Nginx service using systemctl
sudo systemctl stop nginx

# Check Nginx status using systemctl
status=$(sudo systemctl status nginx)

# Check if status indicates that Nginx is not running
if [[ $status == *"inactive"* ]]; then
    echo " * nginx is not running"
fi
